// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEftrRCOig9y2p4sItlFHh432i1mECtbc',
    appId: '1:232600442251:web:6555a7978c471aee724b8e',
    messagingSenderId: '232600442251',
    projectId: 'rso-search',
    authDomain: 'rso-search.firebaseapp.com',
    storageBucket: 'rso-search.appspot.com',
    measurementId: 'G-X612LHP8MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJp1XmKG7DbAbVh44VvyF_WtOHpwkpmBI',
    appId: '1:232600442251:android:902154a1817821dc724b8e',
    messagingSenderId: '232600442251',
    projectId: 'rso-search',
    storageBucket: 'rso-search.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HRexOlm28lK7FGW1SnYavR-sdrh7k4Y',
    appId: '1:232600442251:ios:93f23a385c8e6ba9724b8e',
    messagingSenderId: '232600442251',
    projectId: 'rso-search',
    storageBucket: 'rso-search.appspot.com',
    iosBundleId: 'com.example.rsos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HRexOlm28lK7FGW1SnYavR-sdrh7k4Y',
    appId: '1:232600442251:ios:8e80796e0f4f579d724b8e',
    messagingSenderId: '232600442251',
    projectId: 'rso-search',
    storageBucket: 'rso-search.appspot.com',
    iosBundleId: 'com.example.rsos.RunnerTests',
  );
}
